### ISSUE TITLE
Recaptcha not show

### ISSUE THREAD

**Issue by dsoares** [dsoares/roundcube-rcguard#22]
_From @andrkaz on March 23, 2018 8:30_

After incorrect logins I see message "CAPTCHA verification empty!" but dont see captcha. Also dont working release IP after expire time.
My software:
Sqlite 3-3.22.0
Rcguard version 1.0.10
Roundcube 1.3.4

_Copied from original issue: dsoares/rcguard-old#22_

**Comment by dsoares** [comment]
_From @Imshao on April 29, 2018 18:19_

Try to force https by setting 
`$rcmail_config['recaptcha_https'] = true;`
in your config/config.inc.php file.

Solved the issue for me. The plugin uses `$_SERVER['HTTPS']` to decide wether to use http or https to display reCAPTCHA. If your roundcube installation is on an http server and your site is running behind a revers proxy that does https your browser may not display mixed content correctly.

https://support.mozilla.org/en-US/kb/mixed-content-blocking-firefox

**Comment by dsoares** [comment]
_From @andrkaz on May 2, 2018 11:7_

To Imshao.
I trying, nothing happens...

**Comment by dsoares** [comment]
Please use your browser console to check for errors (Javascript or Network errors).

**Comment by dsoares** [comment]
@Imshao thank you for pointing out that `$_SERVER['HTTPS']` usage. 
I released a new version using the better `rcube_utils::https_check()`.

**Comment by dsoares** [comment]
_From @andrkaz on May 3, 2018 3:23_

No errors in console, but captcha dont show. I enable error log, in log only authorisation errors.
Update: trying Larry and Classic skins

**Comment by dsoares** [comment]
Did you check the Network tab on the Console? All resources are loaded?
What's your plugin configuration?

**Comment by dsoares** [comment]
_From @andrkaz on May 5, 2018 8:57_

I install Rcguard by command "php composer.phar install" after adding rcguard in composer.json. Then register domain in Google and write public and private keys in config.inc.php. I write email to you with my domain, because I dont know what see in console tabs.

**Comment by dsoares** [comment]
Solved with release 1.1.1, which fixes a bug in an sqlite query.
Thank you for helping me spot it.

**Comment by tomcek42** [comment]
I have with version 1.3.1 the same problem. I don't get the captcha after 1 failed login ($config['failed_attempts'] = 1;). I only get the message "CAPTCHA verification empty!"

I'am using version 1.3.1 on RC 1.4.11.

Please, can you help me?

**Comment by alazark94** [comment]
Same issue here RC 1.4.11 rcguard 1.3.1
