### ISSUE TITLE
Invisible reCaptcha

### ISSUE THREAD

**Issue by marki555** [dsoares/roundcube-rcguard#26]
Please add support also for the new Invisible reCaptcha.

**Comment by dsoares** [comment]
Yes, i want to do that, just didn't have the time to test it. But it is in my plans :)

**Comment by dsoares** [comment]
Almost one year later, sorry.
If you didn't already give up, [rcguard release 1.2.1](https://github.com/dsoares/roundcube-rcguard/releases/tag/1.2.1) supports reCAPTCHA v2 invisible and v3.
