### ISSUE TITLE
Missing required parameters: sitekey in console

### ISSUE THREAD

**Issue by TempestaWeb** [dsoares/roundcube-rcguard#28]
I have merged the configuration file and updated it with my public and private key. The API is set to v2. What am I doing wrong? I see no captcha but it locks me out for the grace period.
 
JavaScript console this appears:

uncaught Error: Missing required parameters: sitekey
    at new d$ (recaptcha__en.js:489)
    at new iB (recaptcha__en.js:502)
    at kh (recaptcha__en.js:508)
    at recaptcha__en.js:513
    at Array.forEach (<anonymous>)
    at w$ (recaptcha__en.js:513)
    at Yh (recaptcha__en.js:501)
    at Pd (recaptcha__en.js:498)
    at recaptcha__en.js:514
    at recaptcha__en.js:534

**Comment by dsoares** [comment]
My i see your `rcguard/config.inc.php` file? (of course, remove your site/private keys).
And did you request reCAPTCHA v2 keys? Not v3 nor invisible?

**Comment by dsoares** [comment]
I suppose you figured it out. Closing.
If not, please reopen the issue.
