### ISSUE TITLE
It's not an issue, but version 1.1.2 not available for composer installation

### ISSUE THREAD

**Issue by pablobae** [dsoares/roundcube-rcguard#29]

**Comment by dsoares** [comment]
Yes indeed. I don't understand the problem, i'll look into it later. 
I already tried to release another version, but composer is still stuck in version 1.1.1.

**Comment by pablobae** [comment]
Check Packagist. Mabye it's the cause.

**Comment by dsoares** [comment]
I forgot to check a few days after but now the version is up to date (1.1.3). Since I didn't change nothing, I suppose it was a packaging delay.
