### ISSUE TITLE
elastic skin 1.4.1

### ISSUE THREAD

**Issue by mvldebian** [dsoares/roundcube-rcguard#30]
recaptcha loads misaligned with default css.
I adjusted it to 3% and aligned.

@charset "utf-8";
#login-form .box-inner {background-size:cover}
.g-recaptcha {margin-left:3%}

** On larry file

![image](https://user-images.githubusercontent.com/25337130/69495083-c2dcdf80-0ea1-11ea-9b70-035b3fe10cb8.png)

**Comment by dsoares** [comment]
Thank you for alerting me about it. But i prefer to really align the widget on both sides (it's a very small resize). Released a new version [1.2.2](https://github.com/dsoares/roundcube-rcguard/tree/1.2.2) to fix it and a JS error on elastic skin.
