### ISSUE TITLE
Invisible recaptcha ui issue

### ISSUE THREAD

**Issue by AaronSadlerUK** [dsoares/roundcube-rcguard#31]
As per the image below, the invisible recaptcha ui is all messed up with the new skin

![image](https://user-images.githubusercontent.com/9937803/71386003-ad62ee80-25e2-11ea-9047-5c446fe940d0.png)

**Comment by dsoares** [comment]
Hi,
It does not happen in my environment.
Please tell me the roundcube version and which browser and version do you use. (And which recaptcha version did you put in the plug-in config.inc.php file?)

**Comment by AaronSadlerUK** [comment]
It's roundcube 1.4.1 with rcguard 1.2.2

The version i set in the config is: v2invisible

It can be seen here:
https://webmail.terrabithost.net

I have checked on both Chrome & Firefox

**Comment by purplealert** [comment]
Hello,

I can confirm this issue on my installation.  I've just installed this with the same version & settings and it encroaches the login window in exactly the same way. 

Thanks.

**Comment by dsoares** [comment]
Sorry for the VERY late fix!
[Release 1.3.0](https://github.com/dsoares/roundcube-rcguard/releases/tag/1.3.0) fixes this issue.
