### ISSUE TITLE
Debian 10, RC 1.4.3, roundcube-rcguard 1.2.2 -- Neither ignore IPs nor subnet options are working.

### ISSUE THREAD

**Issue by roylaprattep** [dsoares/roundcube-rcguard#34]
Hi,

Neither

// Do not show recaptcha for this IPs
$rcmail_config['rcguard_ignore_ips'] = array(192.168.1.200);

nor (not at the same time)

// Do not show recaptcha of these networks
$rcmail_config['recaptcha_whitelist'] = array(192.168.1.0/24);

is working.

Plus, when using IP or subnet options (not at the same time...), the Roundcube web page isn't accessible anymore too... Error 500 in any web browser.

Thank you.

**Comment by olegeech-me** [comment]
hey @roylaprattep 
don't forget to quote your networks/ips, the config is a plain php file
```// Do not show recaptcha for this IPs
$rcmail_config['rcguard_ignore_ips'] = array('86.49.236.223');

// Do not show recaptcha of these networks
$rcmail_config['recaptcha_whitelist'] = array('192.168.2.0/23','192.168.5.0/24');
```

**Comment by roylaprattep** [comment]
Hi @olegeech-me 

Oh damn... My bad! I feel stupid.

Working now. ;)

Thank you very much for your help sir.

**Comment by dsoares** [comment]
Thank you @olegeech-me !
