### ISSUE TITLE
Wrong table name

### ISSUE THREAD

**Issue by samuelmf** [dsoares/roundcube-rcguard#35]
On the error log i found several lines like this one:
Table 'username_roun915.rc_rcguard' doesn't exist

That occurs because the php rcguard is not adding the suffix to the table name.

Can i safely rename table name with phpmyadmin? (Well i renamed it manually and all seems to be good)

**Comment by dsoares** [comment]
Hi,
Thank you for submitting this bur report. I'll look into it.

**Comment by dsoares** [comment]
It is not a bug after all. 
The code already uses the Roundcube method to return the correct table name and it is used everywhere.
So i believe you created the database table by hand (like inserting directly into the database the script `SQL/<your_db_driver>.initial.sql`).
